### ISSUE TITLE
ReferenceError: SVGPathElement is not defined

### ISSUE THREAD

**Issue by clarkcb** [davecranwell/svg-to-geojson#5]
I'm trying to use svg-to-geojson as an npm dependency for a rest application, I'm able to install it using `npm install`, but when I try to use it using this require:

`var svgtogeojson = require('svg-to-geojson');`

I get the following error when I try to run the server:

<pre>ReferenceError: SVGPathElement is not defined
    at e.svgtogeojson (path/to/geojson-rest/node_modules/svg-to-geojson/dist/svg-to-geojson.min.js:1:23679)
    at Object.<anonymous> (path/to/geojson-rest/node_modules/svg-to-geojson/dist/svg-to-geojson.min.js:2:22430)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
</pre>

It seems to be an issue related to path-to-polyfill, but I can't figure out how to resolve this.

**Comment by Fil** [comment]
same issue for me

**Comment by sarfatyl** [comment]
same issue for me
